version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - COMMIT_REF=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - BRANCH=master
      - echo build with sha:$COMMIT_REF
      - npm install --only=prod
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync public s3://keycat.co/${COMMIT_REF}
      - aws cloudfront update-distribution --id E1QONAGSSYRR0Z --default-root-object ${COMMIT_REF}/index.html

cache:
  paths:
    - 'node_modules/**/*'
